spring.application.name=blog.service
server.port=8080
#PostgresSql Configuration
spring.datasource.url=jdbc:postgresql://host.docker.internal:49153/blogdb?currentSchema=portfolio
spring.datasource.username=jusmoredb
spring.datasource.password=jusmoredb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Enable virtual threads
#Once set, Spring can run web requests, @Async tasks, and scheduled operations on virtual threads by default.
spring.threads.virtual.enabled=true


# JPA/Hibernate Properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# actuator endoints
#/actuator/env, /actuator/health
#GET http://localhost:8080/actuator/threaddump
management.endpoints.web.exposure.include=threaddump,health,info,env
logging.level.org.springframework.boot.web=DEBUG
management.endpoint.health.show-details=always
management.endpoint.threaddump.enabled=true

# Verify virtual threads via env endpoint
management.endpoint.env.enabled=true
management.endpoint.env.show-values=always

# enable graphql
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql