spring.application.name=blog.service
server.port=8080
#PostgresSql Configuration
spring.datasource.url=jdbc:postgresql://host.docker.internal:49153/blogdb?currentSchema=portfolio
spring.datasource.username=jusmoredb
spring.datasource.password=jusmoredb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# JPA/Hibernate Properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true