# Blog api

openapi: 3.0.0
info:
  title: "Blog platform API"
  version: "1.0.0"
  contact:
    name: Blog service
    email: contact@example.com
    url: https://example.com/
tags:
  - name: BlogService
    description: BlogService related requests
paths:
  /api/v1/blogs:
    post:
      operationId: saveBlog
      summary: Save blog
      tags: [ 'BlogService' ]
      parameters:
        - in: header
          name: X-Idempotency-Key
          required: true
          schema:
            type: string
          description: "Unique identifier for the request to ensure idempotency. Same key will return the same response for duplicate requests."
        - in: header
          name: X-API-Key
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Blog'
      responses:
        '200':
          description: OK
          headers:
            X-RateLimit-Limit:
              schema:
                type: integer
                format: int32
                description: The number of requests allowed per hour
            X-RateLimit-Remaining:
              schema:
                type: integer
                format: int32
                description: The number of requests left for the current rate limit window.
            X-RateLimit-Reset:
              schema:
                type: integer
                format: int32 
                description: The UTC date/time at which the current rate limit window resets.
            X-Idempotency-Key:
              schema:
                type: string  
                description: The idempotency key that was provided in the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog' 
    get:
      operationId: getBlogs
      summary: Get all blogs for the given user id
      tags: [ 'BlogService' ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Blog'

  /api/v1/blogs/{id}:
    get:
      operationId: getBlog
      summary: Get blog by id
      tags: [ 'BlogService' ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'

components:
  schemas:
    Blog:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          maxLength: 255
        slug:
          type: string
          maxLength: 255
        content:
          type: object
        description:
          type: string
        status:
          type: string
          enum:
            - DRAFT
            - PUBLISHED
            - ARCHIVED
        author:
          type: string